name: Deploy

on:
  workflow_dispatch:
  schedule:
    # 08:00 UTC / 00:00 PST / 01:00 PDT
    - cron: '*/5 * * * *'


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Build All The Things
      run: |
        echo "done!"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [build]
    # continue to deply if testing fails
    continue-on-error: true
    steps:
    - name: Test
      run: |
        exit 1

  
  